sources:
  - name: roulette
    handler:
      graphql:
        endpoint: ${PUBLIC_ROULETTE_GRAPH_URL}
  - name: luro
    handler:
      graphql:
        endpoint: ${PUBLIC_LUCKY_ROUND_GRAPH_URL}

codegen:
  scalars:
    BigInt: bigint
    Bytes: string

documents:
  - ./src/schema.graphql