sources:
  - name: roulette
    handler:
      graphql:
        endpoint: ${PUBLIC_ROULETTE_GRAPH_URL}
  - name: predict
    handler:
      graphql:
        endpoint: ${PUBLIC_PREDICT_GRAPH_URL}

codegen:
  scalars:
    BigInt: bigint
    Bytes: string

documents:
  - ./src/schema.graphql